### ISSUE TITLE
Is a python static compatible in hardcore mode, the string


### ISSUE THREAD

**Issue by theyWhoes** [radj307/HARDCORE44#1]
I wrote in my python scrit an blasicisted
 Syntax script to in crease an ratio of precision, aim, and firing.
Its also possible to make a texture boast in the script forum an line of code to replace scr, uv,others in to mapping of an bump map, and uv texturering. As if also when or where you use to file type(.filetype) name of model from to obj, tga, fbx, 3ds and more to enhance resolution. When or not using other script to make texture geometry pull strong been accurate in realistic form.

**Comment by radj307** [comment]
Closed because this doesn't make any sense.  
This mod has nothing to do with anything you mentioned.
