### ISSUE TITLE
Quick question, do i need RCO 22 installed alongside 44?

### ISSUE THREAD

**Issue by devdave** [radj307/HARDCORE44#4]
Trying to figure out if I have a mod conflict or if I need to install RCO 22 along with your mod.

The difficulty is on very hard but enemies are bullet sponges, player health is over 250, and clothing has armor values.  That's with a brand new character.

**Comment by devdave** [comment]
So I tried installing RCO 22 alongside and no luck.  

Next I converted both RCO 22 & 44 to  redmod format and that worked.   I suspect that just bumped the mod(s) priority against another mod that might be in conflict?

**Comment by radj307** [comment]
No need to have RCO installed as well. In fact, it may cause issues having both of them at the same time. They certainly won't work as intended.
